### ISSUE TITLE
remove hardcoded color gray

### ISSUE THREAD

**Issue by hampsterx** [jascodes/animated_indexed_stack#1]
hi there, very handy thnx but can you remove this or allow to be override

```
 return Container(
      color: Colors.grey,
```

**Comment by JasCodes** [comment]
@hampsterx Hey, sure..., I just wrote this for myself and will rewrite to add couple of more features I need. Anyways I am here if you have any questions in future as well :)

**Comment by JasCodes** [comment]
@hampsterx 0.0.7 There you go.. lemme know..

**Comment by JasCodes** [comment]
@hampsterx Btw would love to hear how it was useful to you?

**Comment by hampsterx** [comment]
hi @jascodes cheers for that,  still determining which way to go. Basically I was wanting to have an expanded TabBarView in a Column widget but seems not possible without fixing the height.

https://github.com/flutter/flutter/issues/18711
https://github.com/flutter/flutter/issues/48217

https://stackoverflow.com/questions/52547731/tabbarview-with-variable-height-inside-a-listview

The suggestion there is `IndexedStack` hence I found your package on pub.dev

There is a gist here that I looked at also, after I realised you had hardcoded the background color heh, might want to have a look for inspiration..

https://gist.github.com/diegoveloper/1cd23e79a31d0c18a67424f0cbdfd7ad

I would prefer to use pub package especially if its being improved on. There is a bit of cruft in your code, would be great to clean that up a bit, i'll let you know how it goes, thnx~

**Comment by JasCodes** [comment]
Cool

Though keep in mind, for my use case I am needed not to redraw widgets not stack. Though when I will rewrite this, I will provide way to control that. In my case there were forms, scrolling etc which I just wanted to remain in memory. 

I believe even with tabview you can solve your prob by nicely animating height of the tabview based on the height rendered in child view. Feel free to chat further if interested. You can also connect me at https://LinkedIn.com/in/jascodes and message me thr.

**Comment by JasCodes** [comment]
Closing fixed in 0.0.7
